### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by yufeikang** [oh1ko/am2301#1]
ARCH=arm CROSS_COMPILE= make -C /lib/modules/4.4.9-v7+/build M=/home/pi/project/am2301 modules
make[1]: Entering directory '/lib/modules/4.4.9-v7+/build'
make[1]: **\* No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/lib/modules/4.4.9-v7+/build'
Makefile:6: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by anatolyilin** [comment]
just `make` of if you run in /lib/modules/.../build No such file errors, install headers first with `sudo apt-get install raspberrypi-kernel-headers`
